GET http://localhost:3333/

###

GET http://localhost:3333/cidades

###


GET http://localhost:3333/cidades/1

###

PUT http://localhost:3333/cidades/1
content-type: application/json

{
    "nome": "caxias"  
}

###

DELETE  http://localhost:3333/cidades/1

###

POST http://localhost:3333/cidades
content-type: application/json

{
    "nome": "new city"
}

###

GET http://localhost:3333/pessoas

###


GET http://localhost:3333/pessoas/1

###

POST http://localhost:3333/pessoas
content-type: application/json

{
    "nomeCompleto": "Diego Procopio",
    "email": "maildsss@mail.com",
    "cidadeId": 509
}

###

DELETE http://localhost:3333/pessoas/1

###


PUT http://localhost:3333/pessoas/1
content-type: application/json

{
    "nomeCompleto": "Diego Silva",
    "email": "mail@mail.com",
    "cidadeId": 509
}

###