GET http://localhost:3333/

###

GET http://localhost:3333/cidades

###


GET http://localhost:3333/cidades/1

###

PUT http://localhost:3333/cidades/1
content-type: application/json
Authorization: Bearer 123

{
    "nome": "caxias"  
}

###

DELETE  http://localhost:3333/cidades/1

###

POST http://localhost:3333/cidades
content-type: application/json

{
    "nome": "new city"
}

###

GET http://localhost:3333/pessoas

###


GET http://localhost:3333/pessoas/2

###

POST http://localhost:3333/pessoas
content-type: application/json

{
    "nomeCompleto": "Diego Procopio",
    "email": "mailfddfdsss@mail.com",
    "cidadeId": 509
}

###

DELETE http://localhost:3333/pessoas/2

###


PUT http://localhost:3333/pessoas/3
content-type: application/json

{
    "nomeCompleto": "Diego Silva",
    "email": "mail@mail.com",
    "cidadeId": 509
}

###

POST http://localhost:3333/cadastrar
content-type: application/json

{
    "nome": "Moacir",
    "email": "moados@mail.com",
    "senha": "senha@12"
}

###

POST http://localhost:3333/entrar
content-type: application/json

{
    "email": "moados@mail.com",
    "senha": "senha@12"
}

###